version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:11.10.0
    working_directory: ~/ERC777

commands:
  restore-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package.json" }}
            - v1-dependency-cache-

  restore-build:
    steps:
      - restore_cache:
          keys:
            - v1-build-cache-{{ .BuildNum }}
            - v1-build-cache-

  restore-solc:
    steps:
      - run:
          name: Set write permissions
          command: sudo chmod go+w /opt
      - restore_cache:
          keys:
            - v1-solc-cache-{{ .BuildNum }}
            - v1-solc-cache-
      - run:
          name: Update $PATH
          command: echo 'export PATH="/opt:$PATH"' >> $BASH_ENV

jobs:
  install solc:
    executor: node
    steps:
      - run:
          name: Download solc
          command: curl -L "https://github.com/ethereum/solidity/releases/download/v0.5.3/solc-static-linux" -o /tmp/solc
      - run:
          name: Verify solc download
          command: echo "be08eb95cb3a1da52e918cf51a0c0397fbe7f0693145eb31835bf2924209f1e0 /tmp/solc" | sha256sum -c -
      - run:
          name: Make solc executable
          command: chmod +x /tmp/solc
      - run:
          name: Install solc
          command: sudo mv /tmp/solc /opt/solc
      - save_cache:
          key: v1-solc-cache-{{ .BuildNum }}
          paths:
            - /opt/solc
      - run:
          name: Solc version
          command: /opt/solc --version

  install dependencies:
    executor: node
    steps:
      - checkout
      - run:
          name: Install npm dependencies with npm ci
          command: npm ci
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  build:
    executor: node
    steps:
      - checkout
      - restore-solc
      - restore-dependencies
      - run:
          name: Build Solidity
          command: npm run build
      - save_cache:
          key: v1-build-cache-{{ .BuildNum }}
          paths:
            - ./artifacts

  lint solidity:
    executor: node
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Lint Solidity
          command: npm run lint:sol

  lint javascript:
    executor: node
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Lint JavaScript
          command: npm run lint:js

  test:
    executor: node
    steps:
      - checkout
      - restore-dependencies
      - restore-build
      - restore-solc
      - run:
          name: Test
          command: npm run test

  coverage:
    executor: node
    steps:
      - checkout
      - restore-dependencies
      - restore-build
      - restore-solc
      - run:
          name: Tests with coverage
          command: npm run coverage
      - run:
          name: Install codecov
          command: npm install codecov
      - run:
          name: Report coverage to codecov.io
          command: npx codecov
      - run:
          name: Enforce minimum coverage threshold
          command: npx istanbul check-coverage --statements 95 --functions 95 --branches 95 --lines 95

  publish:
    executor: node
    steps:
      - checkout
      - run:
          name: Verify branch & version tag
          command: .circleci/deploy-check.sh
      - restore-dependencies
      - restore-build
      - restore-solc
      - run:
          name: Set npm auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish

workflows:
  version: 2
  ci_cd:
    jobs:
      - install solc
      - install dependencies
      - build:
          requires:
            - install solc
            - install dependencies
      - lint solidity:
          requires:
            - install dependencies
      - lint javascript:
          requires:
            - install dependencies
      - test:
          requires:
            - lint solidity
            - lint javascript
            - build
      - coverage:
          requires:
            - lint solidity
            - lint javascript
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
